name: 'Get static analysis tools configs'
description: 'This action gets the required configs for the static analysis tools used to check nri-integrations'
inputs:
  repository:
    description: 'Name of the repository to check'
    required: true
    default: 'nri-test'
  semgrep:
    description: 'Get semgrep configuration'
    required: false
    default: 'false'
  golangci-lint:
    description: 'Get golangci-lint configuration'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps: 
    - run: $GITHUB_ACTION_PATH/action.sh
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        SEMGREP: ${{ inputs.semgrep }}
        GOLANGCI_LINT: ${{ inputs.golangci-lint }}