name: Test

on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed
    branches: [ main ]

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: env
