name: Preflight

on:
  pull_request:
  push:

env:
  GO_VERSION: '1.16'

jobs:
  checking_pr:
    name: Preflight
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: env
